### ISSUE TITLE
New timecode is behind last time

### ISSUE THREAD

**Issue by Natarajan92** [pkerling/subconv#1]
Hi, 

We tried to convert the .scc file to .vtt file but we are facing below issues

#subconv -o /mnt/test.vtt test.scc
fatal: Not a git repository (or any of the parent directories): .git
/opt/subconv-master/lib/subconv/scc/reader.rb:242:in `block in read': New timecode is behind last time (Subconv::Scc::Reader::InvalidFormatError)
	from /opt/subconv-master/lib/subconv/scc/reader.rb:231:in `each_line'
	from /opt/subconv-master/lib/subconv/scc/reader.rb:231:in `read'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/subconv-0.1.0/bin/subconv:36:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/subconv-0.1.0/bin/subconv:35:in `open'
	from /usr/local/rvm/gems/ruby-2.2.4/gems/subconv-0.1.0/bin/subconv:35:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.4/bin/subconv:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.4/bin/subconv:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

**Comment by yol** [comment]
Hi,

can you share the scc file please?

**Comment by yol** [comment]
Closing due to lack of response
