### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jfpaulin** [pkerling/subconv#2]
Hi,
First I would like to thank you for developing this gem, this is a great tool!

My boss and I would like to talk with you regarding a feature request. Do you think you can give us your email address or do you want to do this here?

Thanks!

**Comment by yol** [comment]
Happy to see that someone likes it!

> My boss and I would like to talk with you regarding a feature request. Do you think you can give us your email address or do you want to do this here?

That depends - if you are considering to pay for the development (this gem itself arouse from an industry project by the way), please contact me in private. If you just want to make it known that you would find feature XY cool, feel free to open an issue in this repo :-)

You can find my contact address e.g. in the [gemspec](https://github.com/pkerling/subconv/blob/master/subconv.gemspec)
